version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ../:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             celery -A app.core.celery_app worker --loglevel=info"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      REDIS_HOST: redis
    depends_on:
      - redis
volumes:
  postgres_data: